[project]
name = "mini-monoprior"
version = "0.1.0"
description = "Monocular Geometric Priors"
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64"]

[tasks]
xformers-install = {cmd = "python -m pip install xformers --index-url https://download.pytorch.org/whl/cu118", outputs=[".pixi/*"]}
post-install = {cmd = "python -m pip install -e .", depends_on=["xformers-install"], outputs=[".pixi/*"]}
download-example = {cmd = "huggingface-cli download pablovela5620/sample-polycam-room example-room-scan-poly.zip --repo-type dataset --local-dir data/", outputs = ["data/example-room-scan-poly.zip"] }
polycam-inference = {cmd = "python tools/inference_polycam.py --zip-path data/example-room-scan-poly.zip", depends_on=["post-install", "download-example"]}

[dependencies]
python = "3.10.*"
pip = ">=23.3.2,<23.4"
cuda = {version = "*", channel="nvidia/label/cuda-11.8.0"}
pytorch-cuda = {version = "11.8.*", channel="pytorch"}
pytorch = {version = ">=2.2.0,<2.3", channel="pytorch"}
torchvision = {version = ">=0.17.0,<0.18", channel="pytorch"}
rerun-sdk = ">=0.14.1,<0.15"
icecream = ">=2.1.3,<2.2"
jaxtyping = ">=0.2.28,<0.3"
einops = ">=0.7.0,<0.8"
matplotlib = ">=3.8.3,<3.9"
wandb = ">=0.16.5,<0.17"
scipy = ">=1.12.0,<1.13"
timm = ">=0.9.16,<0.10"
pandas = ">=2.2.2,<2.3"
pyarrow = ">=15.0.2,<15.1"
pytorch-lightning = ">=2.2.2,<2.3"

[pypi-dependencies]
huggingface-hub = "*"
opencv-python = "*"
geffnet = "*"
calibur = "==0.0.1"
omnidata-tools = "*"
